version: '3'
services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: "application"
    ports:
      - "8080:8080"
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - application